### ISSUE TITLE
Setting Audio Gain of Channel cannot lower volume

### ISSUE THREAD

**Issue by testhassio** [bitfocus/companion-module-shure-mxn5#2]
I am using companion build 3.4.0, I can turn up the gain on the speakers without issue, if i try to lower the volume it will jump all the way to zero, or will not update at all.
![Image](https://github.com/user-attachments/assets/868ff6a8-eab8-494d-ad3a-ea0adf7c0aeb)

**Comment by dnmeid** [comment]
I have found a bug affecting all values with gains but currently have no hardware to test with.
Can you please test this version: [pkg.zip](https://github.com/user-attachments/files/17526893/pkg.zip)
Please test setting the gain of different channels, incrementing and decrementing the gain of different channels and setting the gain of the signal generator.

There are now also variables that should show the gain of the individual channels (1100 = 0.0dB)

(Howto: [How to use a module that is not included in Companion build](https://github.com/bitfocus/companion/wiki/How-to-use-a-module-that-is-not-included-in-Companion-build))

**Comment by dnmeid** [comment]
@testhassio did you had a chance to test?

**Comment by testhassio** [comment]
I was able to test everything you referenced above successfully. Thanks!

**Comment by dnmeid** [comment]
Cool, then I realease it.
